name: le_cube
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  share_plus: ^3.1.0
  video_player: ^2.2.19
  font_awesome_flutter: ^9.2.0
  form_validator: ^1.0.2
  shared_preferences: ^2.0.13
  file_picker: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/hand_fond.png
    - splashscreen.mp4
    - pres_RR.jpg

